version: '2'
services:
  jhipsterexample-app:
    image: jhipsterexample
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://jhipsterexample-mongodb:27017/?waitQueueMultiple=1000
      - SPRING_DATA_MONGODB_DATABASE=jhipsterexample
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  jhipsterexample-mongodb:
    extends:
      file: mongodb.yml
      service: jhipsterexample-mongodb
